name: OpenTofu Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.6.0
    
    - name: OpenTofu Init (No Backend)
      run: tofu init -backend=false
    
    - name: OpenTofu Format Check
      run: tofu fmt -check
      
    - name: OpenTofu Validate
      run: tofu validate